# Makefile for Writing Make Files Example
# Tabs are required, not tabs
 
# *****************************************************
# Variables to control Makefile operation
 
CC = g++
CFLAGS = -Wall -g
 
# ****************************************************
# Targets needed to bring the executable up to date
 
test: test.o
	$(CC) $(CFLAGS) -o test test.o
 
# The main.o target can be written more simply
 
test.o: test.cpp
	$(CC) $(CFLAGS) -c test.cpp